osx_image: xcode10.1
language: objective-c
script:
- set -o pipefail && xcodebuild test -scheme PagingKit -destination 'platform=iOS Simulator,name=iPhone XS Max,OS=12.1' ONLY_ACTIVE_ARCH=YES | xcpretty
